CREATE TABLE IF NOT EXISTS diagnosis (
    id SERIAL NOT NULL PRIMARY KEY,
    reason VARCHAR(255),
    service_id INT REFERENCES services(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP NULL
);